### ISSUE TITLE
ジャンル検索機能

### ISSUE THREAD

**Issue by barusan-nakanori** [webcamp-aporo/naganocake-of-aporo#55]
TOP、商品一覧、商品詳細でジャンルをクリックした後、商品一覧画面において該当のジャンルに属する商品だけ一覧として表示する機能だと思われます。（通常時は全ての商品を一覧画面では表示）
てつさんがこれから行うかもしれないのですが、一応。

取り敢えず検索機能は置いといて普通にどのジャンルをクリックしても全ての商品を表示する機能でもいいかもしれません。

**Comment by sato-tetsu** [comment]
完成しました。
