### ISSUE TITLE
（低優先）ジャンルステータスの論理削除

### ISSUE THREAD

**Issue by barusan-nakanori** [webcamp-aporo/naganocake-of-aporo#56]
管理者画面で特定のジャンルを無効にしてもTOPページなどではジャンルが全て表示されてしまいます。
無効にしたジャンルは表示できないようにした方がいいと思います。

**Comment by bunashimeji1007** [comment]
paranoiaのGemの機能を使ってできるはずです！
現状「is_delete」のフラグで「有効・無効ステータス」を管理していますが、これはあくまでフラグでしかないので、
論理削除されていない状態です。
なので、ジャンルについても論理削除の機能を反映すればできるはずです！
